//! Acceptance test for AC7 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: ac-judge (cli)
//! AC description: The assembled Anthropic request carries the system block with cache_control {"type":"ephemeral"}; verifiable by inspecting the request body bytes the prompt module produces.
//! Test predicate: tests/acceptance_ac7.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac7` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown, clippy::indexing_slicing, clippy::panic, clippy::as_conversions, clippy::cognitive_complexity, clippy::option_if_let_else, clippy::float_cmp, clippy::float_arithmetic)]

use ac_judge::prompt::build_request;

/// AC7 — the assembled Anthropic request carries the system block with
/// `cache_control: {"type": "ephemeral"}`. Inspect the request body the
/// prompt module produces, end-to-end, including serialization to bytes.
#[test]
fn acceptance_ac7() {
    let req = build_request(
        "claude-sonnet-4-6",
        "output ends with the cut bytes",
        "fn t() { assert_eq!(out.last4(), [0x1D, 0x56, 0x42, 0x00]); }",
        "demo-crate",
        1,
    );

    // Structural check on the value.
    assert_eq!(
        req["system"][0]["cache_control"]["type"], "ephemeral",
        "system block must carry ephemeral cache_control"
    );

    // Byte-level check: the serialized request bytes contain the cache_control
    // directive on the system block (AC7 says "verifiable by inspecting the
    // request body bytes").
    let bytes = serde_json::to_vec(&req).unwrap();
    let body = String::from_utf8(bytes).unwrap();
    assert!(
        body.contains("\"cache_control\":{\"type\":\"ephemeral\"}"),
        "serialized request bytes must contain the ephemeral cache_control; got: {body}"
    );
}
