//! Acceptance test for AC2 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: ac-judge (cli)
//! AC description: DEFERRED to a network iter: a restates-impl test pairing yields assertion_kind:restates-impl with confidence>=0.7 and exit 4.
//! Test predicate: tests/acceptance_ac2.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac2` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown, clippy::indexing_slicing, clippy::panic, clippy::as_conversions, clippy::cognitive_complexity, clippy::option_if_let_else, clippy::float_cmp, clippy::float_arithmetic)]

use std::fs;

use ac_judge::pair::pair_all;
use tempfile::tempdir;

/// AC2 (network-deferred) — a restates-impl test pairing yields
/// `assertion_kind: restates-impl` with confidence >= 0.7 and exit 4.
///
/// The verdict classification is the live judge's job, so the assertion is
/// `#[ignore]`d for the network iteration. Offline, we prove the precondition:
/// the restates-impl fixture is correctly *paired* so the judge will receive
/// it. (The fixture's test merely calls the fn and asserts its own return.)
#[test]
#[ignore = "network: classification is the live judge's job; run with --ignored in the network iter"]
fn acceptance_ac2() {
    let dir = tempdir().unwrap();
    let root = dir.path();
    fs::create_dir_all(root.join("tests")).unwrap();
    // A tautological "restates-impl" test fixture.
    fs::write(
        root.join("tests/ac1_restates.rs"),
        "#[test]\nfn ac1_x() {\n    let got = thing();\n    assert_eq!(got, thing());\n}\n",
    )
    .unwrap();
    let prd = "- **AC1**: the output ends with the cut bytes.\n";
    let pairs = pair_all(prd, root).unwrap();
    assert_eq!(pairs.len(), 1);
    assert!(
        pairs[0].test_path.is_some(),
        "restates-impl fixture must be paired so the judge sees it"
    );
}
