//! Acceptance test for AC3 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: ac-judge (cli)
//! AC description: DEFERRED to a network iter: an asserts-invariant test pairing yields assertion_kind:asserts-invariant and exit 0.
//! Test predicate: tests/acceptance_ac3.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac3` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown, clippy::indexing_slicing, clippy::panic, clippy::as_conversions, clippy::cognitive_complexity, clippy::option_if_let_else, clippy::float_cmp, clippy::float_arithmetic)]

use std::fs;

use ac_judge::pair::pair_all;
use tempfile::tempdir;

/// AC3 (network-deferred) — an asserts-invariant test pairing yields
/// `assertion_kind: asserts-invariant` and exit 0.
///
/// Classification is the live judge's job (`#[ignore]`d for the network iter).
/// Offline, we prove the precondition: the asserts-invariant fixture is
/// correctly paired so the judge receives it.
#[test]
#[ignore = "network: classification is the live judge's job; run with --ignored in the network iter"]
fn acceptance_ac3() {
    let dir = tempdir().unwrap();
    let root = dir.path();
    fs::create_dir_all(root.join("tests")).unwrap();
    // A genuine "asserts-invariant" test fixture: asserts the PRD's English
    // invariant ("ends with the cut bytes") on the result.
    fs::write(
        root.join("tests/ac1_invariant.rs"),
        "#[test]\nfn ac1_x() {\n    let out = render();\n    assert_eq!(&out[out.len()-4..], &[0x1D, 0x56, 0x42, 0x00]);\n}\n",
    )
    .unwrap();
    let prd = "- **AC1**: the output ends with the cut bytes.\n";
    let pairs = pair_all(prd, root).unwrap();
    assert_eq!(pairs.len(), 1);
    assert!(
        pairs[0].test_path.is_some(),
        "asserts-invariant fixture must be paired so the judge sees it"
    );
}
