//! Acceptance test for AC7 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: ac-judge (cli)
//! AC description: The assembled Anthropic request carries the system block with cache_control {"type":"ephemeral"}; verifiable by inspecting the request body bytes the prompt module produces.
//! Test predicate: tests/acceptance_ac7.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac7` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac7() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC7 not yet implemented — see file header");
}
